### ISSUE TITLE
Everything low res on multi monitor

### ISSUE THREAD

**Issue by trbocode** [MultiMC/MultiMC5#2008]
System Information
-----------------------------
MultiMC version: (f06ac02396c8dfd002db80453963cb61bddce080)?
EDIT:Also tested latest

Operating System: Arch Linux

Summary of the issue or suggestion:
----------------------------------------------
The font apprears tiny on multi monitor setups. I have 2 1080p screens and 1 4k screen and I cannot read this in the 1080p monitors and I have to squint to see it on the 4k one.

What should happen:
------------------------------
I should see the font as being larger

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch multimc

2.

3.

Suspected cause:
---------------------------
My primary monitor is the 4K one.

Logs/Screenshots:
----------------------------

![image](https://user-images.githubusercontent.com/20900544/31276430-7019dde2-aaa4-11e7-818c-f3e7db71bb3d.png)

**Comment by peterix** [comment]
Can you reproduce this with the `multimc-git` AUR package?

**Comment by trbocode** [comment]
Same problem.

**Comment by peterix** [comment]
Alright.

What happens when you set this environment variable before running MultiMC?
https://github.com/LMMS/lmms/commit/8a39302571c96e130dd6db1f466011760fd7f1ec#diff-2f50c0e8621ce625bfe4e155028bd5feR11

**Comment by trbocode** [comment]
env QT_AUTO_SCREEN_SCALE_FACTOR=2 multimc
Nothing changes

**Comment by peterix** [comment]
Well, I don't know. I have a large 4k screen, but nothing with high DPI to test with.

This is what the Qt people are saying in their documentation:
http://doc.qt.io/qt-5/highdpi.html

this is the Arch wiki on the same topic:
https://wiki.archlinux.org/index.php/HiDPI#Multiple_displays

The images seem OK... why would it not scale the text?

**Comment by peterix** [comment]
I should be able to replicate this if I fake the physical display sizes in the EDID.

Info: http://kodi.wiki/view/Creating_and_using_edid.bin_via_xorg.conf

**Comment by trbocode** [comment]
My 1080p screen is NOT hidpi
Can you read the text? look, the pictures are in 1080P.
In 4K I have to squint but it's nothing biggie since my monitor is quite big. But I want to run multimc on the 1080p monitor.
BTW, fixed it by using "env QT_SCALE_FACTOR=1.5 multimc"
Howver the fonts are still noticably low res on the 1080P display.

**Comment by phit** [comment]
I'm just gonna hope this is fixed by now since there have been a lot of improvements in the are of scaling in Linux, if not let me know and I'll reopen this.

**Comment by shymega** [comment]
I can confirm that it's still reproducible as described before on Linux. However, I'm using Wayland and Sway. I also have a 4K monitor, but with 155% scaling. I'm also on openSUSE Tumbleweed.

Let me know if you need any further information.

Cheers.

**Comment by phit** [comment]
@shymega please open a new issue, this is about fonts being too small on a 1080p screen when you have multiple monitors

**Comment by shymega** [comment]
@phit You're quite right, my apologies - I misread. I'll check to see if there are any existing issues with my problem first.

**Comment by Djspac3** [comment]
same problem but with mp dual screen on top idk the screen quality tho 
![screen shot](https://github.com/MultiMC/Launcher/assets/149281216/494f813f-9154-465c-b068-23d42485ff81)
 i cant read it but  ![screenshot 2](https://github.com/MultiMC/Launcher/assets/149281216/2f1b7558-779a-4c25-8142-b0c546505867) (on bottom screen

**Comment by Djspac3** [comment]
ooh opps dang it the 1st screen shot
![here](https://github.com/MultiMC/Launcher/assets/149281216/6948f2de-b0df-4b1c-b0bc-980d2f61ac41)

**Comment by phit** [comment]
@Djspac3 use this multimc version https://files.multimc.org/downloads/mmc-develop-win32-5.15.2.zip

**Comment by Djspac3** [comment]
idk what's different but still
![Capture](https://github.com/MultiMC/Launcher/assets/149281216/28bdade6-9f97-4286-b795-db5230b5ef40)
pls say if I need to do something I don't really mess with anything
edit instantly:do i need to do the same env thing?

**Comment by phit** [comment]
I don't see any issue on your new screenshot, no the env stuff isn't applicable for Windows. What are you expecting to see?

**Comment by Djspac3** [comment]
Readable text
Zoom in its unreadable and too small

Also sorry about not responding I RARLY look at my email or apps 😅
