### ISSUE TITLE
New Minecraft snapshots are not compatible

### ISSUE THREAD

**Issue by 3TUSK** [MultiMC/MultiMC5#2026]
System Information
-----------------------------
MultiMC version: 0.6.0-develop-1035

Operating System: macOS Sierra 10.12.6

Summary of the issue or suggestion:
----------------------------------------------
When trying adding a new instance, MultiMC fails to find [17w43a, the most recent snapshot](https://minecraft.net/en-us/article/minecraft-snapshot-17w43a).

What should happen:
------------------------------
According to https://launchermeta.mojang.com/mc/game/version_manifest.json, MultiMC should be able to find the latest snapshot version, and being capable to load it.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Open MultiMC, click "Add Instance"
2. In "Vanilla Minecraft (select version)", click the "..." button
3. Try locate "17w43a". 
4. One should be unable to find such a version under given environment described above. Click "Refresh" to confirm that this is not due to outdated cache.

Suspected cause:
---------------------------
N/A

Logs/Screenshots:
----------------------------
![image](https://user-images.githubusercontent.com/9113033/32017124-a77079e2-b97a-11e7-9d0a-cbd19e811530.png)

Additional Info:
---------------------------
N/A

**Comment by peterix** [comment]
According to meta.multimc.org, there is no such version, and there will be no such version until the required launcher features are implemented.

**Comment by 3TUSK** [comment]
> required launcher features
i.e. the changes in the `17w43a.json`?

**Comment by peterix** [comment]
None of the Mojang files are directly used.

**Comment by peterix** [comment]
The blocking issue for launching these is gone from develop.

Try them out:
[17w43a.zip](https://github.com/MultiMC/MultiMC5/files/1424602/17w43a.zip)
[17w43b.zip](https://github.com/MultiMC/MultiMC5/files/1424603/17w43b.zip)

**Comment by 3TUSK** [comment]
You might want to add some extra jvm arguments for macOS users:

````
---- Minecraft Crash Report ----
// Oops.

Time: 10/28/17 1:47 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:2519)
	at bjr.a(SourceFile:268)
	at bjh.a(SourceFile:716)
	at bjh.ak(SourceFile:434)
	at bjh.a(SourceFile:356)
	at net.minecraft.client.main.Main.main(SourceFile:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:193)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:228)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Caused by: java.lang.IllegalStateException: Please run the JVM with -XstartOnFirstThread and make sure a window toolkit other than GLFW (e.g. AWT or JavaFX) is not initialized.
	at org.lwjgl.glfw.EventLoop$OnScreen.<clinit>(EventLoop.java:63)
	... 14 more
````
(rest of crash-report truncated)

**Comment by peterix** [comment]
I'm just adding it for all versions... assuming the previous ones didn't care about this sort of thing.

**Comment by peterix** [comment]
There was a derp in the previous build. So there is a new one now.
There was also a small issue in the 17w34b instance, so I'm reuploading both:
[17w43a.zip](https://github.com/MultiMC/MultiMC5/files/1424631/17w43a.zip)
[17w43b.zip](https://github.com/MultiMC/MultiMC5/files/1424632/17w43b.zip)

**Comment by peterix** [comment]
@3TUSK try now

**Comment by 3TUSK** [comment]
Tested 17w43b, game starts normally.
> despite the fact that I can't get my trackpad working for Minecraft for unknown reason and I don't have a mouse available nearby...

**Comment by mcdodge34** [comment]
So will we see the new snapshots in the list in MultiMC or we need a special version of MultiMC, I'M in the dev channel and get all new builds, but latest doesn't list the new version still.

**Comment by peterix** [comment]
Well, they seem to be launching correctly now, so I'll start looking into updating the metadata automation so they do show up.

You can import the instances I posted earlier if you want the right now.

**Comment by mcdodge34** [comment]
I'm not in a hurry, will wait for proper support for now, I'M mostly playing heavy modded Minecraft theses days so before we see mods in 1.13, it has to be out of snapshots, so it will take awhile before I need support, but I love to test new features when they are launched in a new snapshot, seems 1.13 won't have that much on this side, just code rewrite.

**Comment by peterix** [comment]
There's some new stuff for map makers and people who run vanilla servers... not much for normal players.

**Comment by 3TUSK** [comment]
Appendix after I got my mouse available: 
MultiMC can handle the launching indeed, but the inputs (keyboard + mouse) are still a mess - most likely due to the upgrade of lwjgl.

**Comment by peterix** [comment]
New instances for the new macOS build:
[17w43a.zip](https://github.com/MultiMC/MultiMC5/files/1424872/17w43a.zip)
[17w43b.zip](https://github.com/MultiMC/MultiMC5/files/1424873/17w43b.zip)

**Comment by peterix** [comment]
Yeah. I see the same sort of terrible input issues. The normal versions are now fine though.

**Comment by peterix** [comment]
I suspect it is caused by the MultiMC launcher part interacting badly with lwjgl3 and whatever is lwjgl3 doing to java runtime...

**Comment by peterix** [comment]
And that experiment did not work.

**Comment by peterix** [comment]
All the launching issues should now be fixed.

**Comment by mcdodge34** [comment]
For me after testing in vanilla launcher, I can't put the fullscreen mode anymore, its like an effect of a stroboscope in fullscreen, but if I launch any other versions including 1.12.2 I don't have this problem, I have same problem when I want to watch steam videos in fullscreen from the steam app, they work fine in browser, but if I want to watch them from the app in fullscreen I get a stroboscope effect that is quite annoying.

**Comment by peterix** [comment]
Well, that's only interesting if it happens in multimc and not in vanilla. It's probably a LWJGL bug. Or some system/gpu driver/dektop environment bug.

**Comment by 3TUSK** [comment]
After updating MultiMC: apparently the mouse & keyboard works again. I believe we can assume the issue is addressed now :)

**Comment by peterix** [comment]
The first part of it, sure. I now need to add automation of processing the new mojang metadata into multimc metadata so it actually shows up in the lists... and change MultiMC some more to handle LWJGL 2 vs LWJGL 3 properly.

**Comment by MulverineX** [comment]
Whats the status on this? Snapshots are still not available for instance creation, and those snapshot instance zips don't work.

**Comment by peterix** [comment]
They do work as long as you are running the dev version of MultiMC.

As for status: not there yet. I will dedicate some time to it, next week.

**Comment by MulverineX** [comment]
How does one join the dev update channel? Is it a separate download? Or a setting somewhere that I missed.

**Comment by 3TUSK** [comment]
@MulverineX , Open MultiMC, click "Settings" on top, you should see something like this:
![image](https://user-images.githubusercontent.com/9113033/32686825-af1b4d08-c662-11e7-9ce7-aa0fc4c01320.png)
And you see that "update channel", which is what peterix mean.

**Comment by peterix** [comment]
The new snapshots:
[17w45a.zip](https://github.com/MultiMC/MultiMC5/files/1464988/17w45a.zip)
[17w45b.zip](https://github.com/MultiMC/MultiMC5/files/1464987/17w45b.zip)

**Comment by ask6155** [comment]
Where do I put these files?

**Comment by peterix** [comment]
Import them. They are instances.

**Comment by peterix** [comment]
And another new snapshot:
[17w46a.zip](https://github.com/MultiMC/MultiMC5/files/1482384/17w46a.zip)

**Comment by 3TUSK** [comment]
@peterix 

````
[17:33:58] [Client thread/ERROR]: Realms module missing
[17:33:59] [Client thread/ERROR]: Realms module missing
````

I don't think there will be people using realms with snapshots... but can you fix this? It is apparently missing in the classpath.

**Comment by MulverineX** [comment]
Also how long until they start showing up in the version list when creating a new instance? I would rather be able to just click the version then import it from here. Which may sometimes be later than the minecraft launcher release.

**Comment by peterix** [comment]
@3TUSK  No, snapshots do not have realms.
@MulverineX When it is done.

**Comment by bballboy2002** [comment]
Do you think this has anything to do with it?
![screen shot 2017-11-21 at 2 06 27p](https://user-images.githubusercontent.com/14823057/33099277-33433a22-cec5-11e7-9100-799cd3df130f.png)

**Comment by peterix** [comment]
That's a small part of it.

**Comment by peterix** [comment]
That sais, I already got it running, but I'm still removing bugs out of the new code...

If you want to try out one of the expermiental builds, here they are:
https://files.multimc.org/downloads/mmc-unstable-win32.zip
https://files.multimc.org/downloads/mmc-unstable-osx64.tar.gz
https://files.multimc.org/downloads/mmc-unstable-lin32.tar.gz
https://files.multimc.org/downloads/mmc-unstable-lin64.tar.gz

**Just don't let it anywhere near your current isntances. Not even from dev. I might have to change things around still and the first thing this does is convert old instances into a new format.**

**Comment by peterix** [comment]
This is now fixed in develop.

**Comment by 3TUSK** [comment]
Confirmed.
![image](https://user-images.githubusercontent.com/9113033/33521201-50cbff8e-d780-11e7-9ccf-7dbc63731aa2.png)

Many thanks on your hard work!
