### ISSUE TITLE
MultiMC data folder could not be created on Mac High Sierra 

### ISSUE THREAD

**Issue by zimmermant** [MultiMC/MultiMC5#2132]
System Information
-----------------------------
MultiMC version:MultiMC 5

Operating System: Mac OS High Sierra v10.13.1 (17B1003)

Summary of the issue or suggestion:
----------------------------------------------
After moving MultiMC to the /Applications folder the pop-up window appears even though the file is in the /Applications folder and states

```
MultiMC data folder could not be created.

If you are on macOS Sierra, you might have to move MultiMC.app to your /Applications or ~/Applications folder. This usually fixes the problem and you can move the application elsewhere afterwards.

Make sure you have the right permissions to the MultiMC data folder and any folder needed to access it.

MultiMC cannot continue until you fix this problem.
```

What should happen:
------------------------------
MultiMC should start

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.  Copy MultiMC to /Applications folder (also tried ~/Applications folder)

2. Double-click to open file

Suspected cause:
---------------------------
Possibly an issue with permissions in High Sierra

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

```
MultiMC data folder could not be created.

If you are on macOS Sierra, you might have to move MultiMC.app to your /Applications or ~/Applications folder. This usually fixes the problem and you can move the application elsewhere afterwards.

Make sure you have the right permissions to the MultiMC data folder and any folder needed to access it.

MultiMC cannot continue until you fix this problem.
```

Additional Info:
---------------------------

**Comment by peterix** [comment]
OK. I'm installing the lates macOS version on a spare partition and will check this out.

**Comment by peterix** [comment]
I cannot reproduce the problem on 10.13.3, so try updating the system?

**Comment by zimmermant** [comment]
I updated to 10.13.3 and I still get the same pop-up.  Any other suggestions?

**Comment by peterix** [comment]
When you grab the release from multimc.org, drag it to Applications (move, not copy) and right click + open, it should work.

It does work here.

I'm honestly not sure what could be causing issues in this case ~_~ You could try looking at the files in terminal and check the permissions.

**Comment by zimmermant** [comment]
Are there any files that need specific permissions?  I did download the latest version of MultiMC and still have the same issue.  The MultiMC file in the MacOS folder has rwx permissions for Owner (700) and the Updater has rwx for Owner and rx for all others (755).

**Comment by peterix** [comment]
That part is fine.

I suspect it's some issue with the extended attributes:

**Comment by zimmermant** [comment]
It turns out this problem is caused by Path Finder 7.6.2.  I was dragging the file into my Applications folder using Path Finder.  If I use the built-in Finder app the file runs fine so my problem is solved.

**Comment by peterix** [comment]
This should be in a FAQ or on the main website.

**Comment by iammeat** [comment]
These steps aren't working for me.  I'm still getting the error whether I unpack and move the app or unpack it into the Applications folder directly.  I'm on 10.13.6.

**Comment by adamras** [comment]
Same issue as iammeat and same fix.  Unzipped in Downloads and then just moved the .app file to /Applications and it executed fine.  If I moved the MultiMC folder with the .app in it, it would not run.
Version 0.6.5-1243 64bit for OSX
<img width="417" alt="Screen Shot 2019-07-05 at 8 37 20 PM" src="https://user-images.githubusercontent.com/24324329/60751042-d58f6000-9f64-11e9-93e9-a712d6ef7e7a.png">

**Comment by efstone** [comment]
This happens for me on any account other than the account that originally installed. macOS El Capitan (not gonna upgrade--the machine is too old)

**Comment by AverageComet250** [comment]
What do you mean by 'any account other than the account that originally installed'. If you mean MMC, then MMC should have a separate install for each user

Thanks,
Shravan Mandava

________________________________

**Comment by efstone** [comment]
> What do you mean by 'any account other than the account that originally installed'. If you mean MMC, then MMC should have a separate install for each user Thanks, Shravan Mandava

Thanks for your response. The accounts I'm referring to are the macOS accounts. I installed MMC logged in as myself and all users of the computer can now see MultiMC.app in the Applications folder, but none of them can actually launch it. When you suggest "a separate install for each user" are you saying that each user download MultiMC and drag it to the Applications folder? Because that will just overwrite the existing MultiMC.app, right? 

El Capitan does not appear to have localized Applications folders per user, but if I need to create them I can.

**Comment by joshuadevp** [comment]
> I suspect it's some issue with the extended attributes: https://mackuba.eu/2008/06/30/ls-on-mac-and-extended-file-attributes/

macOS Monterey 12.2.1

For me, the .app had the "com.apple.quarantine" attribute which wasn't removed when giving the app permission to run. Removing this attribute with `xattr -d com.apple.quarantine MultiMC.app` fixed the issue.
