### ISSUE TITLE
Job 'Mod download' Failed to process

### ISSUE THREAD

**Issue by thundermoon99** [MultiMC/MultiMC5#2846]
System Information
----------------------------- 
MultiMC version: 0.6.7-custom (downloaded from aur)

Operating System: Manjaro Linux 64bit

Summary of the issue or suggestion:
----------------------------------------------
When trying to install a mod pack from curseforge via .zip I wait for about 10-15 minutes for it to "download" and at the very end I'm prompted with an error message that reads "job 'mod download' failed to process"

What should happen:
------------------------------
The mod pack is installed and the game launches? 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download zip from curse forge 

2. Click "add instance"

3. Click " import from zip"

4. Add zip from directory and launch

Suspected cause:
---------------------------
No idea. I've read I need to enable dev options to install mods but I've tried looking for that option and I can't find it. 

Logs/Screenshots:
----------------------------
[Screenshot](https://imgur.com/DMMo6qp) 

Additional Info:
---------------------------
It won't show logs for me even though I set it to do so. I think Minecraft has to be up and running before it shows them to me. Not too entirely sure.

**Comment by thetakodev** [comment]
Same. Worked earlier (15 hours ago) but doesnt anymore

**Comment by thetakodev** [comment]
Here are some logs
https://pastebin.com/PrLeEwZA

**Comment by tehbasshunter** [comment]
@thetakodev I would say create a new issue but the reply would still be the same.  
  
The method we use as the middle man for grabbing the stuff is having issues so importing twitch/curseforge modpacks vial the link are not possible atm.

**Comment by thundermoon99** [comment]
I wasn't using the link I was using a zip I got off of curse/twitch

**Comment by WarpZone32** [comment]
I was able to install the modpack Chemical Exchange from zip today.  Later, I repeatedly failed to install the modpack Glacial Awakening.  Both modpacks are for the 1.12.2 version of minecraft.

What modpacks did you guys try to install that caused the exception?  Maybe if we all compare notes, we can narrow it down to a few mods causing (or at least triggering) the issue?

**Comment by tehbasshunter** [comment]
@WarpZone32 Don't issue hijack. If you're having an issue with the program create a new issue; Not post on someone else's.  
  
@thundermoon99 Considering it's been a month since you opened this issue and I know it should be fixed you mind closing this if it's working now?

**Comment by WarpZone32** [comment]
@tehbasshunter What are you even talking about?  It's the exact same error message.  Google sent me here, I saw another person having the same issue I was having, and I tried to add more information about the problem since none of the previous comemnts said it was fixed or explained what caused it.  Pardon me for trying to help.

**Comment by SpectrumAurami** [comment]
I'm really confused on why this was closed. It's still an issue.

**Comment by phit** [comment]
its closed because its a 3 year old issue with apis that aren't even used anymore, if you are facing download issues make a new issue and provide logs
